server:
  port: 8761

spring:
  application:
    name: jordan

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 6000