package com.f.a.kobe.mapper.previous;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.f.a.kobe.pojo.previous.CustomerScoreTrans;
import com.f.a.kobe.pojo.previous.CustomerScoreTransExample;
@Mapper
public interface CustomerScoreTransMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    int countByExample(CustomerScoreTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerScoreTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    int insert(CustomerScoreTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    int insertSelective(CustomerScoreTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    List<CustomerScoreTrans> selectByExample(CustomerScoreTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    CustomerScoreTrans selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerScoreTrans record, @Param("example") CustomerScoreTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerScoreTrans record, @Param("example") CustomerScoreTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerScoreTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerScoreTrans record);
}