package com.f.a.kobe.pojo.previous;

import java.io.Serializable;
import java.util.Date;

public class CustomerLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.log_channel
     *
     * @mbg.generated
     */
    private Integer logChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.op_type
     *
     * @mbg.generated
     */
    private Integer opType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.ocurr_time
     *
     * @mbg.generated
     */
    private Date ocurrTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.auth_type
     *
     * @mbg.generated
     */
    private Integer authType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.token_expire_time
     *
     * @mbg.generated
     */
    private Date tokenExpireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.ext1
     *
     * @mbg.generated
     */
    private String ext1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.ext2
     *
     * @mbg.generated
     */
    private String ext2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.ext3
     *
     * @mbg.generated
     */
    private String ext3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.ext4
     *
     * @mbg.generated
     */
    private String ext4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.ext5
     *
     * @mbg.generated
     */
    private String ext5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.cdt
     *
     * @mbg.generated
     */
    private Date cdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.mdt
     *
     * @mbg.generated
     */
    private Date mdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.id
     *
     * @return the value of customer_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.id
     *
     * @param id the value for customer_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.customer_id
     *
     * @return the value of customer_log.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.customer_id
     *
     * @param customerId the value for customer_log.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.log_channel
     *
     * @return the value of customer_log.log_channel
     *
     * @mbg.generated
     */
    public Integer getLogChannel() {
        return logChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.log_channel
     *
     * @param logChannel the value for customer_log.log_channel
     *
     * @mbg.generated
     */
    public void setLogChannel(Integer logChannel) {
        this.logChannel = logChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.op_type
     *
     * @return the value of customer_log.op_type
     *
     * @mbg.generated
     */
    public Integer getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.op_type
     *
     * @param opType the value for customer_log.op_type
     *
     * @mbg.generated
     */
    public void setOpType(Integer opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.ocurr_time
     *
     * @return the value of customer_log.ocurr_time
     *
     * @mbg.generated
     */
    public Date getOcurrTime() {
        return ocurrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.ocurr_time
     *
     * @param ocurrTime the value for customer_log.ocurr_time
     *
     * @mbg.generated
     */
    public void setOcurrTime(Date ocurrTime) {
        this.ocurrTime = ocurrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.auth_type
     *
     * @return the value of customer_log.auth_type
     *
     * @mbg.generated
     */
    public Integer getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.auth_type
     *
     * @param authType the value for customer_log.auth_type
     *
     * @mbg.generated
     */
    public void setAuthType(Integer authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.token
     *
     * @return the value of customer_log.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.token
     *
     * @param token the value for customer_log.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.token_expire_time
     *
     * @return the value of customer_log.token_expire_time
     *
     * @mbg.generated
     */
    public Date getTokenExpireTime() {
        return tokenExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.token_expire_time
     *
     * @param tokenExpireTime the value for customer_log.token_expire_time
     *
     * @mbg.generated
     */
    public void setTokenExpireTime(Date tokenExpireTime) {
        this.tokenExpireTime = tokenExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.ext1
     *
     * @return the value of customer_log.ext1
     *
     * @mbg.generated
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.ext1
     *
     * @param ext1 the value for customer_log.ext1
     *
     * @mbg.generated
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.ext2
     *
     * @return the value of customer_log.ext2
     *
     * @mbg.generated
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.ext2
     *
     * @param ext2 the value for customer_log.ext2
     *
     * @mbg.generated
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.ext3
     *
     * @return the value of customer_log.ext3
     *
     * @mbg.generated
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.ext3
     *
     * @param ext3 the value for customer_log.ext3
     *
     * @mbg.generated
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.ext4
     *
     * @return the value of customer_log.ext4
     *
     * @mbg.generated
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.ext4
     *
     * @param ext4 the value for customer_log.ext4
     *
     * @mbg.generated
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.ext5
     *
     * @return the value of customer_log.ext5
     *
     * @mbg.generated
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.ext5
     *
     * @param ext5 the value for customer_log.ext5
     *
     * @mbg.generated
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.cdt
     *
     * @return the value of customer_log.cdt
     *
     * @mbg.generated
     */
    public Date getCdt() {
        return cdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.cdt
     *
     * @param cdt the value for customer_log.cdt
     *
     * @mbg.generated
     */
    public void setCdt(Date cdt) {
        this.cdt = cdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.mdt
     *
     * @return the value of customer_log.mdt
     *
     * @mbg.generated
     */
    public Date getMdt() {
        return mdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.mdt
     *
     * @param mdt the value for customer_log.mdt
     *
     * @mbg.generated
     */
    public void setMdt(Date mdt) {
        this.mdt = mdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CustomerLog other = (CustomerLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getLogChannel() == null ? other.getLogChannel() == null : this.getLogChannel().equals(other.getLogChannel()))
            && (this.getOpType() == null ? other.getOpType() == null : this.getOpType().equals(other.getOpType()))
            && (this.getOcurrTime() == null ? other.getOcurrTime() == null : this.getOcurrTime().equals(other.getOcurrTime()))
            && (this.getAuthType() == null ? other.getAuthType() == null : this.getAuthType().equals(other.getAuthType()))
            && (this.getToken() == null ? other.getToken() == null : this.getToken().equals(other.getToken()))
            && (this.getTokenExpireTime() == null ? other.getTokenExpireTime() == null : this.getTokenExpireTime().equals(other.getTokenExpireTime()))
            && (this.getExt1() == null ? other.getExt1() == null : this.getExt1().equals(other.getExt1()))
            && (this.getExt2() == null ? other.getExt2() == null : this.getExt2().equals(other.getExt2()))
            && (this.getExt3() == null ? other.getExt3() == null : this.getExt3().equals(other.getExt3()))
            && (this.getExt4() == null ? other.getExt4() == null : this.getExt4().equals(other.getExt4()))
            && (this.getExt5() == null ? other.getExt5() == null : this.getExt5().equals(other.getExt5()))
            && (this.getCdt() == null ? other.getCdt() == null : this.getCdt().equals(other.getCdt()))
            && (this.getMdt() == null ? other.getMdt() == null : this.getMdt().equals(other.getMdt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getLogChannel() == null) ? 0 : getLogChannel().hashCode());
        result = prime * result + ((getOpType() == null) ? 0 : getOpType().hashCode());
        result = prime * result + ((getOcurrTime() == null) ? 0 : getOcurrTime().hashCode());
        result = prime * result + ((getAuthType() == null) ? 0 : getAuthType().hashCode());
        result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
        result = prime * result + ((getTokenExpireTime() == null) ? 0 : getTokenExpireTime().hashCode());
        result = prime * result + ((getExt1() == null) ? 0 : getExt1().hashCode());
        result = prime * result + ((getExt2() == null) ? 0 : getExt2().hashCode());
        result = prime * result + ((getExt3() == null) ? 0 : getExt3().hashCode());
        result = prime * result + ((getExt4() == null) ? 0 : getExt4().hashCode());
        result = prime * result + ((getExt5() == null) ? 0 : getExt5().hashCode());
        result = prime * result + ((getCdt() == null) ? 0 : getCdt().hashCode());
        result = prime * result + ((getMdt() == null) ? 0 : getMdt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", customerId=").append(customerId);
        sb.append(", logChannel=").append(logChannel);
        sb.append(", opType=").append(opType);
        sb.append(", ocurrTime=").append(ocurrTime);
        sb.append(", authType=").append(authType);
        sb.append(", token=").append(token);
        sb.append(", tokenExpireTime=").append(tokenExpireTime);
        sb.append(", ext1=").append(ext1);
        sb.append(", ext2=").append(ext2);
        sb.append(", ext3=").append(ext3);
        sb.append(", ext4=").append(ext4);
        sb.append(", ext5=").append(ext5);
        sb.append(", cdt=").append(cdt);
        sb.append(", mdt=").append(mdt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}