package com.f.a.kobe.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CustomerBodyInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    public CustomerBodyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(Long value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(Long value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(Long value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(Long value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(Long value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<Long> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<Long> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(Long value1, Long value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(Long value1, Long value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNull() {
            addCriterion("record_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNotNull() {
            addCriterion("record_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordIdEqualTo(String value) {
            addCriterion("record_id =", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotEqualTo(String value) {
            addCriterion("record_id <>", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThan(String value) {
            addCriterion("record_id >", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThanOrEqualTo(String value) {
            addCriterion("record_id >=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThan(String value) {
            addCriterion("record_id <", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThanOrEqualTo(String value) {
            addCriterion("record_id <=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLike(String value) {
            addCriterion("record_id like", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotLike(String value) {
            addCriterion("record_id not like", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdIn(List<String> values) {
            addCriterion("record_id in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotIn(List<String> values) {
            addCriterion("record_id not in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdBetween(String value1, String value2) {
            addCriterion("record_id between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotBetween(String value1, String value2) {
            addCriterion("record_id not between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIsNull() {
            addCriterion("register_date is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIsNotNull() {
            addCriterion("register_date is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDateEqualTo(Date value) {
            addCriterion("register_date =", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotEqualTo(Date value) {
            addCriterion("register_date <>", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateGreaterThan(Date value) {
            addCriterion("register_date >", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateGreaterThanOrEqualTo(Date value) {
            addCriterion("register_date >=", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateLessThan(Date value) {
            addCriterion("register_date <", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateLessThanOrEqualTo(Date value) {
            addCriterion("register_date <=", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIn(List<Date> values) {
            addCriterion("register_date in", values, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotIn(List<Date> values) {
            addCriterion("register_date not in", values, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateBetween(Date value1, Date value2) {
            addCriterion("register_date between", value1, value2, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotBetween(Date value1, Date value2) {
            addCriterion("register_date not between", value1, value2, "registerDate");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(String value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(String value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(String value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(String value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(String value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(String value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLike(String value) {
            addCriterion("height like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotLike(String value) {
            addCriterion("height not like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<String> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<String> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(String value1, String value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(String value1, String value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(String value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(String value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(String value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(String value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(String value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(String value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLike(String value) {
            addCriterion("weight like", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotLike(String value) {
            addCriterion("weight not like", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<String> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<String> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(String value1, String value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(String value1, String value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andChestIsNull() {
            addCriterion("chest is null");
            return (Criteria) this;
        }

        public Criteria andChestIsNotNull() {
            addCriterion("chest is not null");
            return (Criteria) this;
        }

        public Criteria andChestEqualTo(String value) {
            addCriterion("chest =", value, "chest");
            return (Criteria) this;
        }

        public Criteria andChestNotEqualTo(String value) {
            addCriterion("chest <>", value, "chest");
            return (Criteria) this;
        }

        public Criteria andChestGreaterThan(String value) {
            addCriterion("chest >", value, "chest");
            return (Criteria) this;
        }

        public Criteria andChestGreaterThanOrEqualTo(String value) {
            addCriterion("chest >=", value, "chest");
            return (Criteria) this;
        }

        public Criteria andChestLessThan(String value) {
            addCriterion("chest <", value, "chest");
            return (Criteria) this;
        }

        public Criteria andChestLessThanOrEqualTo(String value) {
            addCriterion("chest <=", value, "chest");
            return (Criteria) this;
        }

        public Criteria andChestLike(String value) {
            addCriterion("chest like", value, "chest");
            return (Criteria) this;
        }

        public Criteria andChestNotLike(String value) {
            addCriterion("chest not like", value, "chest");
            return (Criteria) this;
        }

        public Criteria andChestIn(List<String> values) {
            addCriterion("chest in", values, "chest");
            return (Criteria) this;
        }

        public Criteria andChestNotIn(List<String> values) {
            addCriterion("chest not in", values, "chest");
            return (Criteria) this;
        }

        public Criteria andChestBetween(String value1, String value2) {
            addCriterion("chest between", value1, value2, "chest");
            return (Criteria) this;
        }

        public Criteria andChestNotBetween(String value1, String value2) {
            addCriterion("chest not between", value1, value2, "chest");
            return (Criteria) this;
        }

        public Criteria andWaistlineIsNull() {
            addCriterion("waistline is null");
            return (Criteria) this;
        }

        public Criteria andWaistlineIsNotNull() {
            addCriterion("waistline is not null");
            return (Criteria) this;
        }

        public Criteria andWaistlineEqualTo(String value) {
            addCriterion("waistline =", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineNotEqualTo(String value) {
            addCriterion("waistline <>", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineGreaterThan(String value) {
            addCriterion("waistline >", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineGreaterThanOrEqualTo(String value) {
            addCriterion("waistline >=", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineLessThan(String value) {
            addCriterion("waistline <", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineLessThanOrEqualTo(String value) {
            addCriterion("waistline <=", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineLike(String value) {
            addCriterion("waistline like", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineNotLike(String value) {
            addCriterion("waistline not like", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineIn(List<String> values) {
            addCriterion("waistline in", values, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineNotIn(List<String> values) {
            addCriterion("waistline not in", values, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineBetween(String value1, String value2) {
            addCriterion("waistline between", value1, value2, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineNotBetween(String value1, String value2) {
            addCriterion("waistline not between", value1, value2, "waistline");
            return (Criteria) this;
        }

        public Criteria andHiplineIsNull() {
            addCriterion("hipline is null");
            return (Criteria) this;
        }

        public Criteria andHiplineIsNotNull() {
            addCriterion("hipline is not null");
            return (Criteria) this;
        }

        public Criteria andHiplineEqualTo(String value) {
            addCriterion("hipline =", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineNotEqualTo(String value) {
            addCriterion("hipline <>", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineGreaterThan(String value) {
            addCriterion("hipline >", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineGreaterThanOrEqualTo(String value) {
            addCriterion("hipline >=", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineLessThan(String value) {
            addCriterion("hipline <", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineLessThanOrEqualTo(String value) {
            addCriterion("hipline <=", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineLike(String value) {
            addCriterion("hipline like", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineNotLike(String value) {
            addCriterion("hipline not like", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineIn(List<String> values) {
            addCriterion("hipline in", values, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineNotIn(List<String> values) {
            addCriterion("hipline not in", values, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineBetween(String value1, String value2) {
            addCriterion("hipline between", value1, value2, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineNotBetween(String value1, String value2) {
            addCriterion("hipline not between", value1, value2, "hipline");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioIsNull() {
            addCriterion("waist_hip_ratio is null");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioIsNotNull() {
            addCriterion("waist_hip_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioEqualTo(String value) {
            addCriterion("waist_hip_ratio =", value, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioNotEqualTo(String value) {
            addCriterion("waist_hip_ratio <>", value, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioGreaterThan(String value) {
            addCriterion("waist_hip_ratio >", value, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioGreaterThanOrEqualTo(String value) {
            addCriterion("waist_hip_ratio >=", value, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioLessThan(String value) {
            addCriterion("waist_hip_ratio <", value, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioLessThanOrEqualTo(String value) {
            addCriterion("waist_hip_ratio <=", value, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioLike(String value) {
            addCriterion("waist_hip_ratio like", value, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioNotLike(String value) {
            addCriterion("waist_hip_ratio not like", value, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioIn(List<String> values) {
            addCriterion("waist_hip_ratio in", values, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioNotIn(List<String> values) {
            addCriterion("waist_hip_ratio not in", values, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioBetween(String value1, String value2) {
            addCriterion("waist_hip_ratio between", value1, value2, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andWaistHipRatioNotBetween(String value1, String value2) {
            addCriterion("waist_hip_ratio not between", value1, value2, "waistHipRatio");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceIsNull() {
            addCriterion("left_arm_circumference is null");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceIsNotNull() {
            addCriterion("left_arm_circumference is not null");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceEqualTo(String value) {
            addCriterion("left_arm_circumference =", value, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceNotEqualTo(String value) {
            addCriterion("left_arm_circumference <>", value, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceGreaterThan(String value) {
            addCriterion("left_arm_circumference >", value, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceGreaterThanOrEqualTo(String value) {
            addCriterion("left_arm_circumference >=", value, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceLessThan(String value) {
            addCriterion("left_arm_circumference <", value, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceLessThanOrEqualTo(String value) {
            addCriterion("left_arm_circumference <=", value, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceLike(String value) {
            addCriterion("left_arm_circumference like", value, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceNotLike(String value) {
            addCriterion("left_arm_circumference not like", value, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceIn(List<String> values) {
            addCriterion("left_arm_circumference in", values, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceNotIn(List<String> values) {
            addCriterion("left_arm_circumference not in", values, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceBetween(String value1, String value2) {
            addCriterion("left_arm_circumference between", value1, value2, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftArmCircumferenceNotBetween(String value1, String value2) {
            addCriterion("left_arm_circumference not between", value1, value2, "leftArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceIsNull() {
            addCriterion("right_arm_circumference is null");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceIsNotNull() {
            addCriterion("right_arm_circumference is not null");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceEqualTo(String value) {
            addCriterion("right_arm_circumference =", value, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceNotEqualTo(String value) {
            addCriterion("right_arm_circumference <>", value, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceGreaterThan(String value) {
            addCriterion("right_arm_circumference >", value, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceGreaterThanOrEqualTo(String value) {
            addCriterion("right_arm_circumference >=", value, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceLessThan(String value) {
            addCriterion("right_arm_circumference <", value, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceLessThanOrEqualTo(String value) {
            addCriterion("right_arm_circumference <=", value, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceLike(String value) {
            addCriterion("right_arm_circumference like", value, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceNotLike(String value) {
            addCriterion("right_arm_circumference not like", value, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceIn(List<String> values) {
            addCriterion("right_arm_circumference in", values, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceNotIn(List<String> values) {
            addCriterion("right_arm_circumference not in", values, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceBetween(String value1, String value2) {
            addCriterion("right_arm_circumference between", value1, value2, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andRightArmCircumferenceNotBetween(String value1, String value2) {
            addCriterion("right_arm_circumference not between", value1, value2, "rightArmCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceIsNull() {
            addCriterion("left_thigh_circumference is null");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceIsNotNull() {
            addCriterion("left_thigh_circumference is not null");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceEqualTo(String value) {
            addCriterion("left_thigh_circumference =", value, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceNotEqualTo(String value) {
            addCriterion("left_thigh_circumference <>", value, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceGreaterThan(String value) {
            addCriterion("left_thigh_circumference >", value, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceGreaterThanOrEqualTo(String value) {
            addCriterion("left_thigh_circumference >=", value, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceLessThan(String value) {
            addCriterion("left_thigh_circumference <", value, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceLessThanOrEqualTo(String value) {
            addCriterion("left_thigh_circumference <=", value, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceLike(String value) {
            addCriterion("left_thigh_circumference like", value, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceNotLike(String value) {
            addCriterion("left_thigh_circumference not like", value, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceIn(List<String> values) {
            addCriterion("left_thigh_circumference in", values, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceNotIn(List<String> values) {
            addCriterion("left_thigh_circumference not in", values, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceBetween(String value1, String value2) {
            addCriterion("left_thigh_circumference between", value1, value2, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andLeftThighCircumferenceNotBetween(String value1, String value2) {
            addCriterion("left_thigh_circumference not between", value1, value2, "leftThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceIsNull() {
            addCriterion("right_thigh_circumference is null");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceIsNotNull() {
            addCriterion("right_thigh_circumference is not null");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceEqualTo(String value) {
            addCriterion("right_thigh_circumference =", value, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceNotEqualTo(String value) {
            addCriterion("right_thigh_circumference <>", value, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceGreaterThan(String value) {
            addCriterion("right_thigh_circumference >", value, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceGreaterThanOrEqualTo(String value) {
            addCriterion("right_thigh_circumference >=", value, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceLessThan(String value) {
            addCriterion("right_thigh_circumference <", value, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceLessThanOrEqualTo(String value) {
            addCriterion("right_thigh_circumference <=", value, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceLike(String value) {
            addCriterion("right_thigh_circumference like", value, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceNotLike(String value) {
            addCriterion("right_thigh_circumference not like", value, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceIn(List<String> values) {
            addCriterion("right_thigh_circumference in", values, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceNotIn(List<String> values) {
            addCriterion("right_thigh_circumference not in", values, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceBetween(String value1, String value2) {
            addCriterion("right_thigh_circumference between", value1, value2, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andRightThighCircumferenceNotBetween(String value1, String value2) {
            addCriterion("right_thigh_circumference not between", value1, value2, "rightThighCircumference");
            return (Criteria) this;
        }

        public Criteria andFatPercentageIsNull() {
            addCriterion("\"fat percentage\" is null");
            return (Criteria) this;
        }

        public Criteria andFatPercentageIsNotNull() {
            addCriterion("\"fat percentage\" is not null");
            return (Criteria) this;
        }

        public Criteria andFatPercentageEqualTo(String value) {
            addCriterion("\"fat percentage\" =", value, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andFatPercentageNotEqualTo(String value) {
            addCriterion("\"fat percentage\" <>", value, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andFatPercentageGreaterThan(String value) {
            addCriterion("\"fat percentage\" >", value, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andFatPercentageGreaterThanOrEqualTo(String value) {
            addCriterion("\"fat percentage\" >=", value, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andFatPercentageLessThan(String value) {
            addCriterion("\"fat percentage\" <", value, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andFatPercentageLessThanOrEqualTo(String value) {
            addCriterion("\"fat percentage\" <=", value, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andFatPercentageLike(String value) {
            addCriterion("\"fat percentage\" like", value, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andFatPercentageNotLike(String value) {
            addCriterion("\"fat percentage\" not like", value, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andFatPercentageIn(List<String> values) {
            addCriterion("\"fat percentage\" in", values, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andFatPercentageNotIn(List<String> values) {
            addCriterion("\"fat percentage\" not in", values, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andFatPercentageBetween(String value1, String value2) {
            addCriterion("\"fat percentage\" between", value1, value2, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andFatPercentageNotBetween(String value1, String value2) {
            addCriterion("\"fat percentage\" not between", value1, value2, "fatPercentage");
            return (Criteria) this;
        }

        public Criteria andHeartRateIsNull() {
            addCriterion("heart_rate is null");
            return (Criteria) this;
        }

        public Criteria andHeartRateIsNotNull() {
            addCriterion("heart_rate is not null");
            return (Criteria) this;
        }

        public Criteria andHeartRateEqualTo(String value) {
            addCriterion("heart_rate =", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotEqualTo(String value) {
            addCriterion("heart_rate <>", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateGreaterThan(String value) {
            addCriterion("heart_rate >", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateGreaterThanOrEqualTo(String value) {
            addCriterion("heart_rate >=", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateLessThan(String value) {
            addCriterion("heart_rate <", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateLessThanOrEqualTo(String value) {
            addCriterion("heart_rate <=", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateLike(String value) {
            addCriterion("heart_rate like", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotLike(String value) {
            addCriterion("heart_rate not like", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateIn(List<String> values) {
            addCriterion("heart_rate in", values, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotIn(List<String> values) {
            addCriterion("heart_rate not in", values, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateBetween(String value1, String value2) {
            addCriterion("heart_rate between", value1, value2, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotBetween(String value1, String value2) {
            addCriterion("heart_rate not between", value1, value2, "heartRate");
            return (Criteria) this;
        }

        public Criteria andSdpIsNull() {
            addCriterion("sdp is null");
            return (Criteria) this;
        }

        public Criteria andSdpIsNotNull() {
            addCriterion("sdp is not null");
            return (Criteria) this;
        }

        public Criteria andSdpEqualTo(String value) {
            addCriterion("sdp =", value, "sdp");
            return (Criteria) this;
        }

        public Criteria andSdpNotEqualTo(String value) {
            addCriterion("sdp <>", value, "sdp");
            return (Criteria) this;
        }

        public Criteria andSdpGreaterThan(String value) {
            addCriterion("sdp >", value, "sdp");
            return (Criteria) this;
        }

        public Criteria andSdpGreaterThanOrEqualTo(String value) {
            addCriterion("sdp >=", value, "sdp");
            return (Criteria) this;
        }

        public Criteria andSdpLessThan(String value) {
            addCriterion("sdp <", value, "sdp");
            return (Criteria) this;
        }

        public Criteria andSdpLessThanOrEqualTo(String value) {
            addCriterion("sdp <=", value, "sdp");
            return (Criteria) this;
        }

        public Criteria andSdpLike(String value) {
            addCriterion("sdp like", value, "sdp");
            return (Criteria) this;
        }

        public Criteria andSdpNotLike(String value) {
            addCriterion("sdp not like", value, "sdp");
            return (Criteria) this;
        }

        public Criteria andSdpIn(List<String> values) {
            addCriterion("sdp in", values, "sdp");
            return (Criteria) this;
        }

        public Criteria andSdpNotIn(List<String> values) {
            addCriterion("sdp not in", values, "sdp");
            return (Criteria) this;
        }

        public Criteria andSdpBetween(String value1, String value2) {
            addCriterion("sdp between", value1, value2, "sdp");
            return (Criteria) this;
        }

        public Criteria andSdpNotBetween(String value1, String value2) {
            addCriterion("sdp not between", value1, value2, "sdp");
            return (Criteria) this;
        }

        public Criteria andDbpIsNull() {
            addCriterion("dbp is null");
            return (Criteria) this;
        }

        public Criteria andDbpIsNotNull() {
            addCriterion("dbp is not null");
            return (Criteria) this;
        }

        public Criteria andDbpEqualTo(String value) {
            addCriterion("dbp =", value, "dbp");
            return (Criteria) this;
        }

        public Criteria andDbpNotEqualTo(String value) {
            addCriterion("dbp <>", value, "dbp");
            return (Criteria) this;
        }

        public Criteria andDbpGreaterThan(String value) {
            addCriterion("dbp >", value, "dbp");
            return (Criteria) this;
        }

        public Criteria andDbpGreaterThanOrEqualTo(String value) {
            addCriterion("dbp >=", value, "dbp");
            return (Criteria) this;
        }

        public Criteria andDbpLessThan(String value) {
            addCriterion("dbp <", value, "dbp");
            return (Criteria) this;
        }

        public Criteria andDbpLessThanOrEqualTo(String value) {
            addCriterion("dbp <=", value, "dbp");
            return (Criteria) this;
        }

        public Criteria andDbpLike(String value) {
            addCriterion("dbp like", value, "dbp");
            return (Criteria) this;
        }

        public Criteria andDbpNotLike(String value) {
            addCriterion("dbp not like", value, "dbp");
            return (Criteria) this;
        }

        public Criteria andDbpIn(List<String> values) {
            addCriterion("dbp in", values, "dbp");
            return (Criteria) this;
        }

        public Criteria andDbpNotIn(List<String> values) {
            addCriterion("dbp not in", values, "dbp");
            return (Criteria) this;
        }

        public Criteria andDbpBetween(String value1, String value2) {
            addCriterion("dbp between", value1, value2, "dbp");
            return (Criteria) this;
        }

        public Criteria andDbpNotBetween(String value1, String value2) {
            addCriterion("dbp not between", value1, value2, "dbp");
            return (Criteria) this;
        }

        public Criteria andFatContentIsNull() {
            addCriterion("fat_content is null");
            return (Criteria) this;
        }

        public Criteria andFatContentIsNotNull() {
            addCriterion("fat_content is not null");
            return (Criteria) this;
        }

        public Criteria andFatContentEqualTo(String value) {
            addCriterion("fat_content =", value, "fatContent");
            return (Criteria) this;
        }

        public Criteria andFatContentNotEqualTo(String value) {
            addCriterion("fat_content <>", value, "fatContent");
            return (Criteria) this;
        }

        public Criteria andFatContentGreaterThan(String value) {
            addCriterion("fat_content >", value, "fatContent");
            return (Criteria) this;
        }

        public Criteria andFatContentGreaterThanOrEqualTo(String value) {
            addCriterion("fat_content >=", value, "fatContent");
            return (Criteria) this;
        }

        public Criteria andFatContentLessThan(String value) {
            addCriterion("fat_content <", value, "fatContent");
            return (Criteria) this;
        }

        public Criteria andFatContentLessThanOrEqualTo(String value) {
            addCriterion("fat_content <=", value, "fatContent");
            return (Criteria) this;
        }

        public Criteria andFatContentLike(String value) {
            addCriterion("fat_content like", value, "fatContent");
            return (Criteria) this;
        }

        public Criteria andFatContentNotLike(String value) {
            addCriterion("fat_content not like", value, "fatContent");
            return (Criteria) this;
        }

        public Criteria andFatContentIn(List<String> values) {
            addCriterion("fat_content in", values, "fatContent");
            return (Criteria) this;
        }

        public Criteria andFatContentNotIn(List<String> values) {
            addCriterion("fat_content not in", values, "fatContent");
            return (Criteria) this;
        }

        public Criteria andFatContentBetween(String value1, String value2) {
            addCriterion("fat_content between", value1, value2, "fatContent");
            return (Criteria) this;
        }

        public Criteria andFatContentNotBetween(String value1, String value2) {
            addCriterion("fat_content not between", value1, value2, "fatContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentIsNull() {
            addCriterion("muscle_content is null");
            return (Criteria) this;
        }

        public Criteria andMuscleContentIsNotNull() {
            addCriterion("muscle_content is not null");
            return (Criteria) this;
        }

        public Criteria andMuscleContentEqualTo(String value) {
            addCriterion("muscle_content =", value, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentNotEqualTo(String value) {
            addCriterion("muscle_content <>", value, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentGreaterThan(String value) {
            addCriterion("muscle_content >", value, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentGreaterThanOrEqualTo(String value) {
            addCriterion("muscle_content >=", value, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentLessThan(String value) {
            addCriterion("muscle_content <", value, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentLessThanOrEqualTo(String value) {
            addCriterion("muscle_content <=", value, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentLike(String value) {
            addCriterion("muscle_content like", value, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentNotLike(String value) {
            addCriterion("muscle_content not like", value, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentIn(List<String> values) {
            addCriterion("muscle_content in", values, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentNotIn(List<String> values) {
            addCriterion("muscle_content not in", values, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentBetween(String value1, String value2) {
            addCriterion("muscle_content between", value1, value2, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andMuscleContentNotBetween(String value1, String value2) {
            addCriterion("muscle_content not between", value1, value2, "muscleContent");
            return (Criteria) this;
        }

        public Criteria andExt1IsNull() {
            addCriterion("ext1 is null");
            return (Criteria) this;
        }

        public Criteria andExt1IsNotNull() {
            addCriterion("ext1 is not null");
            return (Criteria) this;
        }

        public Criteria andExt1EqualTo(String value) {
            addCriterion("ext1 =", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotEqualTo(String value) {
            addCriterion("ext1 <>", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1GreaterThan(String value) {
            addCriterion("ext1 >", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1GreaterThanOrEqualTo(String value) {
            addCriterion("ext1 >=", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1LessThan(String value) {
            addCriterion("ext1 <", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1LessThanOrEqualTo(String value) {
            addCriterion("ext1 <=", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1Like(String value) {
            addCriterion("ext1 like", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotLike(String value) {
            addCriterion("ext1 not like", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1In(List<String> values) {
            addCriterion("ext1 in", values, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotIn(List<String> values) {
            addCriterion("ext1 not in", values, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1Between(String value1, String value2) {
            addCriterion("ext1 between", value1, value2, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotBetween(String value1, String value2) {
            addCriterion("ext1 not between", value1, value2, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt2IsNull() {
            addCriterion("ext2 is null");
            return (Criteria) this;
        }

        public Criteria andExt2IsNotNull() {
            addCriterion("ext2 is not null");
            return (Criteria) this;
        }

        public Criteria andExt2EqualTo(String value) {
            addCriterion("ext2 =", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotEqualTo(String value) {
            addCriterion("ext2 <>", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2GreaterThan(String value) {
            addCriterion("ext2 >", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2GreaterThanOrEqualTo(String value) {
            addCriterion("ext2 >=", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2LessThan(String value) {
            addCriterion("ext2 <", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2LessThanOrEqualTo(String value) {
            addCriterion("ext2 <=", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2Like(String value) {
            addCriterion("ext2 like", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotLike(String value) {
            addCriterion("ext2 not like", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2In(List<String> values) {
            addCriterion("ext2 in", values, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotIn(List<String> values) {
            addCriterion("ext2 not in", values, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2Between(String value1, String value2) {
            addCriterion("ext2 between", value1, value2, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotBetween(String value1, String value2) {
            addCriterion("ext2 not between", value1, value2, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt3IsNull() {
            addCriterion("ext3 is null");
            return (Criteria) this;
        }

        public Criteria andExt3IsNotNull() {
            addCriterion("ext3 is not null");
            return (Criteria) this;
        }

        public Criteria andExt3EqualTo(String value) {
            addCriterion("ext3 =", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3NotEqualTo(String value) {
            addCriterion("ext3 <>", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3GreaterThan(String value) {
            addCriterion("ext3 >", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3GreaterThanOrEqualTo(String value) {
            addCriterion("ext3 >=", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3LessThan(String value) {
            addCriterion("ext3 <", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3LessThanOrEqualTo(String value) {
            addCriterion("ext3 <=", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3Like(String value) {
            addCriterion("ext3 like", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3NotLike(String value) {
            addCriterion("ext3 not like", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3In(List<String> values) {
            addCriterion("ext3 in", values, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3NotIn(List<String> values) {
            addCriterion("ext3 not in", values, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3Between(String value1, String value2) {
            addCriterion("ext3 between", value1, value2, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3NotBetween(String value1, String value2) {
            addCriterion("ext3 not between", value1, value2, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt4IsNull() {
            addCriterion("ext4 is null");
            return (Criteria) this;
        }

        public Criteria andExt4IsNotNull() {
            addCriterion("ext4 is not null");
            return (Criteria) this;
        }

        public Criteria andExt4EqualTo(String value) {
            addCriterion("ext4 =", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4NotEqualTo(String value) {
            addCriterion("ext4 <>", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4GreaterThan(String value) {
            addCriterion("ext4 >", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4GreaterThanOrEqualTo(String value) {
            addCriterion("ext4 >=", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4LessThan(String value) {
            addCriterion("ext4 <", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4LessThanOrEqualTo(String value) {
            addCriterion("ext4 <=", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4Like(String value) {
            addCriterion("ext4 like", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4NotLike(String value) {
            addCriterion("ext4 not like", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4In(List<String> values) {
            addCriterion("ext4 in", values, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4NotIn(List<String> values) {
            addCriterion("ext4 not in", values, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4Between(String value1, String value2) {
            addCriterion("ext4 between", value1, value2, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4NotBetween(String value1, String value2) {
            addCriterion("ext4 not between", value1, value2, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt5IsNull() {
            addCriterion("ext5 is null");
            return (Criteria) this;
        }

        public Criteria andExt5IsNotNull() {
            addCriterion("ext5 is not null");
            return (Criteria) this;
        }

        public Criteria andExt5EqualTo(String value) {
            addCriterion("ext5 =", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5NotEqualTo(String value) {
            addCriterion("ext5 <>", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5GreaterThan(String value) {
            addCriterion("ext5 >", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5GreaterThanOrEqualTo(String value) {
            addCriterion("ext5 >=", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5LessThan(String value) {
            addCriterion("ext5 <", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5LessThanOrEqualTo(String value) {
            addCriterion("ext5 <=", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5Like(String value) {
            addCriterion("ext5 like", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5NotLike(String value) {
            addCriterion("ext5 not like", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5In(List<String> values) {
            addCriterion("ext5 in", values, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5NotIn(List<String> values) {
            addCriterion("ext5 not in", values, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5Between(String value1, String value2) {
            addCriterion("ext5 between", value1, value2, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5NotBetween(String value1, String value2) {
            addCriterion("ext5 not between", value1, value2, "ext5");
            return (Criteria) this;
        }

        public Criteria andBmiIsNull() {
            addCriterion("bmi is null");
            return (Criteria) this;
        }

        public Criteria andBmiIsNotNull() {
            addCriterion("bmi is not null");
            return (Criteria) this;
        }

        public Criteria andBmiEqualTo(String value) {
            addCriterion("bmi =", value, "bmi");
            return (Criteria) this;
        }

        public Criteria andBmiNotEqualTo(String value) {
            addCriterion("bmi <>", value, "bmi");
            return (Criteria) this;
        }

        public Criteria andBmiGreaterThan(String value) {
            addCriterion("bmi >", value, "bmi");
            return (Criteria) this;
        }

        public Criteria andBmiGreaterThanOrEqualTo(String value) {
            addCriterion("bmi >=", value, "bmi");
            return (Criteria) this;
        }

        public Criteria andBmiLessThan(String value) {
            addCriterion("bmi <", value, "bmi");
            return (Criteria) this;
        }

        public Criteria andBmiLessThanOrEqualTo(String value) {
            addCriterion("bmi <=", value, "bmi");
            return (Criteria) this;
        }

        public Criteria andBmiLike(String value) {
            addCriterion("bmi like", value, "bmi");
            return (Criteria) this;
        }

        public Criteria andBmiNotLike(String value) {
            addCriterion("bmi not like", value, "bmi");
            return (Criteria) this;
        }

        public Criteria andBmiIn(List<String> values) {
            addCriterion("bmi in", values, "bmi");
            return (Criteria) this;
        }

        public Criteria andBmiNotIn(List<String> values) {
            addCriterion("bmi not in", values, "bmi");
            return (Criteria) this;
        }

        public Criteria andBmiBetween(String value1, String value2) {
            addCriterion("bmi between", value1, value2, "bmi");
            return (Criteria) this;
        }

        public Criteria andBmiNotBetween(String value1, String value2) {
            addCriterion("bmi not between", value1, value2, "bmi");
            return (Criteria) this;
        }

        public Criteria andCdtIsNull() {
            addCriterion("cdt is null");
            return (Criteria) this;
        }

        public Criteria andCdtIsNotNull() {
            addCriterion("cdt is not null");
            return (Criteria) this;
        }

        public Criteria andCdtEqualTo(Date value) {
            addCriterionForJDBCDate("cdt =", value, "cdt");
            return (Criteria) this;
        }

        public Criteria andCdtNotEqualTo(Date value) {
            addCriterionForJDBCDate("cdt <>", value, "cdt");
            return (Criteria) this;
        }

        public Criteria andCdtGreaterThan(Date value) {
            addCriterionForJDBCDate("cdt >", value, "cdt");
            return (Criteria) this;
        }

        public Criteria andCdtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cdt >=", value, "cdt");
            return (Criteria) this;
        }

        public Criteria andCdtLessThan(Date value) {
            addCriterionForJDBCDate("cdt <", value, "cdt");
            return (Criteria) this;
        }

        public Criteria andCdtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cdt <=", value, "cdt");
            return (Criteria) this;
        }

        public Criteria andCdtIn(List<Date> values) {
            addCriterionForJDBCDate("cdt in", values, "cdt");
            return (Criteria) this;
        }

        public Criteria andCdtNotIn(List<Date> values) {
            addCriterionForJDBCDate("cdt not in", values, "cdt");
            return (Criteria) this;
        }

        public Criteria andCdtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cdt between", value1, value2, "cdt");
            return (Criteria) this;
        }

        public Criteria andCdtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cdt not between", value1, value2, "cdt");
            return (Criteria) this;
        }

        public Criteria andMdtIsNull() {
            addCriterion("mdt is null");
            return (Criteria) this;
        }

        public Criteria andMdtIsNotNull() {
            addCriterion("mdt is not null");
            return (Criteria) this;
        }

        public Criteria andMdtEqualTo(Date value) {
            addCriterionForJDBCDate("mdt =", value, "mdt");
            return (Criteria) this;
        }

        public Criteria andMdtNotEqualTo(Date value) {
            addCriterionForJDBCDate("mdt <>", value, "mdt");
            return (Criteria) this;
        }

        public Criteria andMdtGreaterThan(Date value) {
            addCriterionForJDBCDate("mdt >", value, "mdt");
            return (Criteria) this;
        }

        public Criteria andMdtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("mdt >=", value, "mdt");
            return (Criteria) this;
        }

        public Criteria andMdtLessThan(Date value) {
            addCriterionForJDBCDate("mdt <", value, "mdt");
            return (Criteria) this;
        }

        public Criteria andMdtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("mdt <=", value, "mdt");
            return (Criteria) this;
        }

        public Criteria andMdtIn(List<Date> values) {
            addCriterionForJDBCDate("mdt in", values, "mdt");
            return (Criteria) this;
        }

        public Criteria andMdtNotIn(List<Date> values) {
            addCriterionForJDBCDate("mdt not in", values, "mdt");
            return (Criteria) this;
        }

        public Criteria andMdtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("mdt between", value1, value2, "mdt");
            return (Criteria) this;
        }

        public Criteria andMdtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("mdt not between", value1, value2, "mdt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_body_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_body_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}