package com.f.a.kobe.pojo;

import java.io.Serializable;
import java.util.Date;

public class CustomerScoreTrans implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.trans_no
     *
     * @mbggenerated
     */
    private Long transNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.trans_type
     *
     * @mbggenerated
     */
    private String transType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.trans_count
     *
     * @mbggenerated
     */
    private Integer transCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.customer_score
     *
     * @mbggenerated
     */
    private Integer customerScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.ext1
     *
     * @mbggenerated
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.ext2
     *
     * @mbggenerated
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.ext3
     *
     * @mbggenerated
     */
    private String ext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.ext4
     *
     * @mbggenerated
     */
    private String ext4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.ext5
     *
     * @mbggenerated
     */
    private String ext5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.cdt
     *
     * @mbggenerated
     */
    private Date cdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_score_trans.mdt
     *
     * @mbggenerated
     */
    private Date mdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.id
     *
     * @return the value of customer_score_trans.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.id
     *
     * @param id the value for customer_score_trans.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.trans_no
     *
     * @return the value of customer_score_trans.trans_no
     *
     * @mbggenerated
     */
    public Long getTransNo() {
        return transNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.trans_no
     *
     * @param transNo the value for customer_score_trans.trans_no
     *
     * @mbggenerated
     */
    public void setTransNo(Long transNo) {
        this.transNo = transNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.customer_id
     *
     * @return the value of customer_score_trans.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.customer_id
     *
     * @param customerId the value for customer_score_trans.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.trans_type
     *
     * @return the value of customer_score_trans.trans_type
     *
     * @mbggenerated
     */
    public String getTransType() {
        return transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.trans_type
     *
     * @param transType the value for customer_score_trans.trans_type
     *
     * @mbggenerated
     */
    public void setTransType(String transType) {
        this.transType = transType == null ? null : transType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.trans_count
     *
     * @return the value of customer_score_trans.trans_count
     *
     * @mbggenerated
     */
    public Integer getTransCount() {
        return transCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.trans_count
     *
     * @param transCount the value for customer_score_trans.trans_count
     *
     * @mbggenerated
     */
    public void setTransCount(Integer transCount) {
        this.transCount = transCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.customer_score
     *
     * @return the value of customer_score_trans.customer_score
     *
     * @mbggenerated
     */
    public Integer getCustomerScore() {
        return customerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.customer_score
     *
     * @param customerScore the value for customer_score_trans.customer_score
     *
     * @mbggenerated
     */
    public void setCustomerScore(Integer customerScore) {
        this.customerScore = customerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.ext1
     *
     * @return the value of customer_score_trans.ext1
     *
     * @mbggenerated
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.ext1
     *
     * @param ext1 the value for customer_score_trans.ext1
     *
     * @mbggenerated
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.ext2
     *
     * @return the value of customer_score_trans.ext2
     *
     * @mbggenerated
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.ext2
     *
     * @param ext2 the value for customer_score_trans.ext2
     *
     * @mbggenerated
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.ext3
     *
     * @return the value of customer_score_trans.ext3
     *
     * @mbggenerated
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.ext3
     *
     * @param ext3 the value for customer_score_trans.ext3
     *
     * @mbggenerated
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.ext4
     *
     * @return the value of customer_score_trans.ext4
     *
     * @mbggenerated
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.ext4
     *
     * @param ext4 the value for customer_score_trans.ext4
     *
     * @mbggenerated
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.ext5
     *
     * @return the value of customer_score_trans.ext5
     *
     * @mbggenerated
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.ext5
     *
     * @param ext5 the value for customer_score_trans.ext5
     *
     * @mbggenerated
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.cdt
     *
     * @return the value of customer_score_trans.cdt
     *
     * @mbggenerated
     */
    public Date getCdt() {
        return cdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.cdt
     *
     * @param cdt the value for customer_score_trans.cdt
     *
     * @mbggenerated
     */
    public void setCdt(Date cdt) {
        this.cdt = cdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_score_trans.mdt
     *
     * @return the value of customer_score_trans.mdt
     *
     * @mbggenerated
     */
    public Date getMdt() {
        return mdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_score_trans.mdt
     *
     * @param mdt the value for customer_score_trans.mdt
     *
     * @mbggenerated
     */
    public void setMdt(Date mdt) {
        this.mdt = mdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CustomerScoreTrans other = (CustomerScoreTrans) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTransNo() == null ? other.getTransNo() == null : this.getTransNo().equals(other.getTransNo()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getTransType() == null ? other.getTransType() == null : this.getTransType().equals(other.getTransType()))
            && (this.getTransCount() == null ? other.getTransCount() == null : this.getTransCount().equals(other.getTransCount()))
            && (this.getCustomerScore() == null ? other.getCustomerScore() == null : this.getCustomerScore().equals(other.getCustomerScore()))
            && (this.getExt1() == null ? other.getExt1() == null : this.getExt1().equals(other.getExt1()))
            && (this.getExt2() == null ? other.getExt2() == null : this.getExt2().equals(other.getExt2()))
            && (this.getExt3() == null ? other.getExt3() == null : this.getExt3().equals(other.getExt3()))
            && (this.getExt4() == null ? other.getExt4() == null : this.getExt4().equals(other.getExt4()))
            && (this.getExt5() == null ? other.getExt5() == null : this.getExt5().equals(other.getExt5()))
            && (this.getCdt() == null ? other.getCdt() == null : this.getCdt().equals(other.getCdt()))
            && (this.getMdt() == null ? other.getMdt() == null : this.getMdt().equals(other.getMdt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTransNo() == null) ? 0 : getTransNo().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getTransType() == null) ? 0 : getTransType().hashCode());
        result = prime * result + ((getTransCount() == null) ? 0 : getTransCount().hashCode());
        result = prime * result + ((getCustomerScore() == null) ? 0 : getCustomerScore().hashCode());
        result = prime * result + ((getExt1() == null) ? 0 : getExt1().hashCode());
        result = prime * result + ((getExt2() == null) ? 0 : getExt2().hashCode());
        result = prime * result + ((getExt3() == null) ? 0 : getExt3().hashCode());
        result = prime * result + ((getExt4() == null) ? 0 : getExt4().hashCode());
        result = prime * result + ((getExt5() == null) ? 0 : getExt5().hashCode());
        result = prime * result + ((getCdt() == null) ? 0 : getCdt().hashCode());
        result = prime * result + ((getMdt() == null) ? 0 : getMdt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", transNo=").append(transNo);
        sb.append(", customerId=").append(customerId);
        sb.append(", transType=").append(transType);
        sb.append(", transCount=").append(transCount);
        sb.append(", customerScore=").append(customerScore);
        sb.append(", ext1=").append(ext1);
        sb.append(", ext2=").append(ext2);
        sb.append(", ext3=").append(ext3);
        sb.append(", ext4=").append(ext4);
        sb.append(", ext5=").append(ext5);
        sb.append(", cdt=").append(cdt);
        sb.append(", mdt=").append(mdt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}