package com.f.a.kobe.pojo;

import java.io.Serializable;
import java.util.Date;

public class CustomerCredential implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.wx_openid
     *
     * @mbg.generated
     */
    private String wxOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.ali_openid
     *
     * @mbg.generated
     */
    private String aliOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.ext1
     *
     * @mbg.generated
     */
    private String ext1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.ext2
     *
     * @mbg.generated
     */
    private String ext2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.ext3
     *
     * @mbg.generated
     */
    private String ext3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.ext4
     *
     * @mbg.generated
     */
    private String ext4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.ext5
     *
     * @mbg.generated
     */
    private String ext5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.dr
     *
     * @mbg.generated
     */
    private String dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.cdt
     *
     * @mbg.generated
     */
    private Date cdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_credential.mdt
     *
     * @mbg.generated
     */
    private Date mdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.id
     *
     * @return the value of customer_credential.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.id
     *
     * @param id the value for customer_credential.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.customer_id
     *
     * @return the value of customer_credential.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.customer_id
     *
     * @param customerId the value for customer_credential.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.mobile
     *
     * @return the value of customer_credential.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.mobile
     *
     * @param mobile the value for customer_credential.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.wx_openid
     *
     * @return the value of customer_credential.wx_openid
     *
     * @mbg.generated
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.wx_openid
     *
     * @param wxOpenid the value for customer_credential.wx_openid
     *
     * @mbg.generated
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.ali_openid
     *
     * @return the value of customer_credential.ali_openid
     *
     * @mbg.generated
     */
    public String getAliOpenid() {
        return aliOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.ali_openid
     *
     * @param aliOpenid the value for customer_credential.ali_openid
     *
     * @mbg.generated
     */
    public void setAliOpenid(String aliOpenid) {
        this.aliOpenid = aliOpenid == null ? null : aliOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.username
     *
     * @return the value of customer_credential.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.username
     *
     * @param username the value for customer_credential.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.password
     *
     * @return the value of customer_credential.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.password
     *
     * @param password the value for customer_credential.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.email
     *
     * @return the value of customer_credential.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.email
     *
     * @param email the value for customer_credential.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.ext1
     *
     * @return the value of customer_credential.ext1
     *
     * @mbg.generated
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.ext1
     *
     * @param ext1 the value for customer_credential.ext1
     *
     * @mbg.generated
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.ext2
     *
     * @return the value of customer_credential.ext2
     *
     * @mbg.generated
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.ext2
     *
     * @param ext2 the value for customer_credential.ext2
     *
     * @mbg.generated
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.ext3
     *
     * @return the value of customer_credential.ext3
     *
     * @mbg.generated
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.ext3
     *
     * @param ext3 the value for customer_credential.ext3
     *
     * @mbg.generated
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.ext4
     *
     * @return the value of customer_credential.ext4
     *
     * @mbg.generated
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.ext4
     *
     * @param ext4 the value for customer_credential.ext4
     *
     * @mbg.generated
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.ext5
     *
     * @return the value of customer_credential.ext5
     *
     * @mbg.generated
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.ext5
     *
     * @param ext5 the value for customer_credential.ext5
     *
     * @mbg.generated
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.dr
     *
     * @return the value of customer_credential.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.dr
     *
     * @param dr the value for customer_credential.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.cdt
     *
     * @return the value of customer_credential.cdt
     *
     * @mbg.generated
     */
    public Date getCdt() {
        return cdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.cdt
     *
     * @param cdt the value for customer_credential.cdt
     *
     * @mbg.generated
     */
    public void setCdt(Date cdt) {
        this.cdt = cdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_credential.mdt
     *
     * @return the value of customer_credential.mdt
     *
     * @mbg.generated
     */
    public Date getMdt() {
        return mdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_credential.mdt
     *
     * @param mdt the value for customer_credential.mdt
     *
     * @mbg.generated
     */
    public void setMdt(Date mdt) {
        this.mdt = mdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CustomerCredential other = (CustomerCredential) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getWxOpenid() == null ? other.getWxOpenid() == null : this.getWxOpenid().equals(other.getWxOpenid()))
            && (this.getAliOpenid() == null ? other.getAliOpenid() == null : this.getAliOpenid().equals(other.getAliOpenid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getExt1() == null ? other.getExt1() == null : this.getExt1().equals(other.getExt1()))
            && (this.getExt2() == null ? other.getExt2() == null : this.getExt2().equals(other.getExt2()))
            && (this.getExt3() == null ? other.getExt3() == null : this.getExt3().equals(other.getExt3()))
            && (this.getExt4() == null ? other.getExt4() == null : this.getExt4().equals(other.getExt4()))
            && (this.getExt5() == null ? other.getExt5() == null : this.getExt5().equals(other.getExt5()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getCdt() == null ? other.getCdt() == null : this.getCdt().equals(other.getCdt()))
            && (this.getMdt() == null ? other.getMdt() == null : this.getMdt().equals(other.getMdt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getWxOpenid() == null) ? 0 : getWxOpenid().hashCode());
        result = prime * result + ((getAliOpenid() == null) ? 0 : getAliOpenid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getExt1() == null) ? 0 : getExt1().hashCode());
        result = prime * result + ((getExt2() == null) ? 0 : getExt2().hashCode());
        result = prime * result + ((getExt3() == null) ? 0 : getExt3().hashCode());
        result = prime * result + ((getExt4() == null) ? 0 : getExt4().hashCode());
        result = prime * result + ((getExt5() == null) ? 0 : getExt5().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getCdt() == null) ? 0 : getCdt().hashCode());
        result = prime * result + ((getMdt() == null) ? 0 : getMdt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", customerId=").append(customerId);
        sb.append(", mobile=").append(mobile);
        sb.append(", wxOpenid=").append(wxOpenid);
        sb.append(", aliOpenid=").append(aliOpenid);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", ext1=").append(ext1);
        sb.append(", ext2=").append(ext2);
        sb.append(", ext3=").append(ext3);
        sb.append(", ext4=").append(ext4);
        sb.append(", ext5=").append(ext5);
        sb.append(", dr=").append(dr);
        sb.append(", cdt=").append(cdt);
        sb.append(", mdt=").append(mdt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}