server:
  port: 8762
spring:
  application:
    name: david
  cloud:
    config:
      server:
        git:
         #uri: https://github.com/micezhao/spring-cloud-demo.git    # 配置git仓库的地址
         uri: https://github.com/micezhao/config-fit.git
         # git仓库地址下的相对地址，可以配置多个，用,分割。
         #search-paths: 
         username: micezhao                                           # git仓库的账号
         password: micezhao1017                                       # git仓库的密码
  rabbitmq:
    #host: 118.190.53.214
    #port: 5682
    host: 39.100.131.79
    port: 5672
    #username: micezhao
    #password: micezhao1017
    virtual-host: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://39.100.131.79:8761/eureka/
  instance:
    #hostname: imac-david ## 通过hostname注册到eureka
    lease-expiration-duration-in-seconds: 5 #设置心跳的周期间隔(默认90s)[如果5s没响应默认服务宕机]
    lease-renewal-interval-in-seconds: 3  #设置心跳时间间隔(默认30s)
    prefer-ip-address: true       #访问路径变为IP地址
    #通过主机名是，注释掉下面的配置
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    instance-id: ${spring.application.name}:${server.port}
    
management:
  security:
    enabled: false