server:
  port: 8762
spring:
  application:
    name: david
  cloud:
    config:
      label: master
      server:
        git:
         uri: https://github.com/micezhao/fit-eat.git
         #uri: https://github.com/micezhao/config-center.git
         searchPaths: config
         username: micezhao
         password: micezhao1017
  rabbitmq:
    host: 118.190.53.214
    port: 5682
    username: micezhao
    password: Zc881017
    virtual-host: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   ## 注册中心eurka地址

management:
  security:
    enabled: false
