package com.f.a.kobe.mapper;

import com.f.a.kobe.pojo.China;
import com.f.a.kobe.pojo.ChinaExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ChinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated
     */
    long countByExample(ChinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated
     */
    int deleteByExample(ChinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated
     */
    int insert(China record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated
     */
    int insertSelective(China record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated
     */
    List<China> selectByExample(ChinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated
     */
    China selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") China record, @Param("example") ChinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") China record, @Param("example") ChinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(China record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(China record);
}