package com.f.a.kobe.mapper;

import com.f.a.kobe.pojo.CustomerScoreTrans;
import com.f.a.kobe.pojo.CustomerScoreTransExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CustomerScoreTransMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbg.generated
     */
    long countByExample(CustomerScoreTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerScoreTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbg.generated
     */
    int insert(CustomerScoreTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbg.generated
     */
    int insertSelective(CustomerScoreTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbg.generated
     */
    List<CustomerScoreTrans> selectByExample(CustomerScoreTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbg.generated
     */
    CustomerScoreTrans selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomerScoreTrans record, @Param("example") CustomerScoreTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomerScoreTrans record, @Param("example") CustomerScoreTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerScoreTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_score_trans
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerScoreTrans record);
}