package com.f.a.kobe.mapper;

import com.f.a.kobe.pojo.CustomerLog;
import com.f.a.kobe.pojo.CustomerLogExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CustomerLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    long countByExample(CustomerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    int insert(CustomerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    int insertSelective(CustomerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    List<CustomerLog> selectByExample(CustomerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    CustomerLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomerLog record, @Param("example") CustomerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomerLog record, @Param("example") CustomerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerLog record);
}