package com.f.a.kobe.mapper;

import com.f.a.kobe.pojo.CustomerCredential;
import com.f.a.kobe.pojo.CustomerCredentialExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CustomerCredentialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    long countByExample(CustomerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    int insert(CustomerCredential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    int insertSelective(CustomerCredential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    List<CustomerCredential> selectByExample(CustomerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    CustomerCredential selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomerCredential record, @Param("example") CustomerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomerCredential record, @Param("example") CustomerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerCredential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerCredential record);
}