package com.f.a.kobe.mapper;

import com.f.a.kobe.pojo.CustomerBaseInfo;
import com.f.a.kobe.pojo.CustomerBaseInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CustomerBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_baseinfo
     *
     * @mbggenerated
     */
    int countByExample(CustomerBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_baseinfo
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_baseinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_baseinfo
     *
     * @mbggenerated
     */
    int insert(CustomerBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_baseinfo
     *
     * @mbggenerated
     */
    int insertSelective(CustomerBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_baseinfo
     *
     * @mbggenerated
     */
    List<CustomerBaseInfo> selectByExample(CustomerBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_baseinfo
     *
     * @mbggenerated
     */
    CustomerBaseInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_baseinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerBaseInfo record, @Param("example") CustomerBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_baseinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerBaseInfo record, @Param("example") CustomerBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_baseinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_baseinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerBaseInfo record);
}