package com.f.a.kobe.mapper;

import com.f.a.kobe.pojo.CustomerAddr;
import com.f.a.kobe.pojo.CustomerAddrExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CustomerAddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated
     */
    long countByExample(CustomerAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated
     */
    int insert(CustomerAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated
     */
    int insertSelective(CustomerAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated
     */
    List<CustomerAddr> selectByExample(CustomerAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated
     */
    CustomerAddr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomerAddr record, @Param("example") CustomerAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomerAddr record, @Param("example") CustomerAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerAddr record);
}